# Generated by Django 6.0.1 on 2026-01-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('points_per_game', models.FloatField()),
                ('rebounds_per_game', models.FloatField()),
                ('assists_per_game', models.FloatField()),
                ('availability', models.IntegerField(choices=[(1, 'Available'), (2, 'Day-to-Day'), (3, 'Out')], default=1)),
            ],
        ),
    ]
